class DummyData {
  static List<Map<String, dynamic>> dummyList = [
    {
      'id': 1,
      'babyFirstName': 'John',
      'doctorName': 'Dr. Smith',
      'father': 'Mr. Johnson',
      'hospitalName': 'City Hospital',
      'mother': 'Mrs. Johnson',
      'placeOfBirth': 'New York',
      'tenantId': 'T123',
    },
    {
      'id': 2,
      'babyFirstName': 'Emily',
      'doctorName': 'Dr. Brown',
      'father': 'Mr. Davis',
      'hospitalName': 'Community Hospital',
      'mother': 'Mrs. Davis',
      'placeOfBirth': 'Los Angeles',
      'tenantId': 'T17890',
    },
    {
      'id': 3,
      'babyFirstName': 'John',
      'doctorName': 'Dr. Smith',
      'father': 'Mr. Johnson',
      'hospitalName': 'City Hospital',
      'mother': 'Mrs. Johnson',
      'placeOfBirth': 'New York',
      'tenantId': 'T1234',
    },
    {
      'id': 4,
      'babyFirstName': 'John',
      'doctorName': 'Dr. Smith',
      'father': 'Mr. Johnson',
      'hospitalName': 'City Hospital',
      'mother': 'Mrs. Johnson',
      'placeOfBirth': 'New York',
      'tenantId': 'T12',
    },
    {
      'id': 5,
      'babyFirstName': 'John',
      'doctorName': 'Dr. Smith',
      'father': 'Mr. Johnson',
      'hospitalName': 'City Hospital',
      'mother': 'Mrs. Johnson',
      'placeOfBirth': 'New York',
      'tenantId': 'T12345',
    },
  ];
}
